# Generated by Django 4.0.6 on 2022-08-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
